services:

  site1:
    image: site1-image
    container_name: site1-container
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - /home/docker_sites/site1:/usr/share/nginx/html
