services:

  site1:
    image: site1-image
    container_name: site1-container
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - /home/docker_sites/site1:/usr/share/nginx/html


  site2:
    image: site2-image
    container_name: site2-container
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - /home/docker_sites/site2:/usr/share/nginx/html


  site3:
    image: site3-image
    container_name: site3-container
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - /home/docker_sites/site3:/usr/share/nginx/html
